# ONNX model paths
det_model_path: "models/ml_PP-OCRv3_det.onnx"
rec_model_path: "models/en_PP-OCRv3_rec.onnx"
char_dict_path: "models/en_dict.txt"

# ONNX runtime configuration
providers: ["CPUExecutionProvider"]

# Detection parameters
box_threshold: 0.3
min_area: 1000
unclip_ratio: 2.0
poly_approx_eps: 0.01

# Recognition parameters
rec_height: 48
target_size: [960, 960]

# Normalization parameters
det_norm_mean: [0.485, 0.456, 0.406]
det_norm_std: [0.229, 0.224, 0.225]
rec_norm_mean: [0.5, 0.5, 0.5]
rec_norm_std: [0.5, 0.5, 0.5] 